robot_radius: 0.07
# map_type: costmap
obstacle_range: 120
raytrace_range: 2.5
publish_voxel_map: true
observation_sources: laser_scan
laser_scan:
  sensor_frame: laser
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true
  min_obstacle_height: -0.10
  max_obstacle_height: 2.0
