global_costmap:
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 0.5
  resolution: 0.05
  rolling_window: false
  transform_tolerance: 1.0 
  cost_scaling_factor: 5.0
  inflation_radius: 0.10
  width: 10.0
  height: 10.0

  static_layer:
    map_topic: /map
    # map_type: costmap
    track_unknown_space: false
    subscribe_to_updates: true

  inflation_layer:
    inflation_radius: 0.15